# Schema for the configuration files of the New Theme theme.
new_theme.settings:
  type: theme_settings
  label: 'New Theme settings'
  mapping:
    font_size:
      type: integer
      label: Font size
